title: Rosemary Wang
description: she/her. infra engineer. cloud explorer.
url: https://joatmon08.com
baseurl: ""

markdown: kramdown

sass:
  style: compressed

# Social links
x_url: https://x.com/joatmon08
bluesky_url: https://bsky.app/profile/joatmon08.com
github_url: https://github.com/joatmon08
linkedin_url: https://www.linkedin.com/in/rosemarywang/
devto_url: https://dev.to/joatmon08
medium_url: https://medium.com/@joatmon08

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - scripts/
  - .bundle/
  - vendor/
  - preview.sh
